### ISSUE TITLE
Country code ERROR

### ISSUE THREAD

**Issue by aestendrela** [saifalisew1508/Telegram-Members-Adder#12]
I'm trying to configure the bot with a number from Spain +34
When I try, I get the following error : Enter Phone Number With Country Code
I've tried with +34..., 0034.... but it doesn't work at all! Could you help me? How do I have to enter it?

Thank you very much for all your contributions!
You are amazing!

**Comment by saifalisew1508** [comment]
please send me screenshot at instagram(saifalisew1508), whatsapp(+919708973259) or telegram(UnknownSaif)

**Comment by saifalisew1508** [comment]
please send me screenshot at instagram(saifalisew1508), whatsapp(+919708973259) or telegram(UnknownSaif)
