### ISSUE TITLE
request to add feature

### ISSUE THREAD

**Issue by mnbhaker** [saifalisew1508/Telegram-Members-Adder#2]
brother can you please add load data with csv file

**Comment by cryptoexpertssss** [comment]
![image](https://user-images.githubusercontent.com/101889698/160245010-1f2471cf-dfe1-4c3a-a9fc-009f0c3bb219.png)


[*] -- Adding members from 31 account(s) --
[+] User: XXXXXXXXXX -- Starting session...
[+] User: Hedge -- Joined group to scrape
[+] User: Hedge -- Joined group to add
[+] User: Hedge -- Retrieving entities...
[!] Couldn't scrape members
[!] 'ChannelParticipants' object is not subscriptable
[+] User: XXXXXXXXXX -- Starting session...
[+] User: Mark -- Joined group to scrape
[+] User: Mark -- Joined group to add
[+] User: Mark -- Retrieving entities...
[!] Couldn't scrape members
[!] 'ChannelParticipants' object is not subscriptable
[+] User: XXXXXXXXXX -- Starting session...
[+] User: Adam -- Joined group to scrape
[+] User: Adam -- Joined group to add
[+] User: Adam -- Retrieving entities...
[!] Couldn't scrape members
[!] 'ChannelParticipants' object is not subscriptable
[+] User: XXXXXXXXXX -- Starting session...
[+] User: Robert -- Joined group to scrape
[+] User: Robert -- Joined group to add
[+] User: Robert -- Retrieving entities...
[!] Couldn't scrape members
[!] 'ChannelParticipants' object is not subscriptable
[+] User: XXXXXXXXXX -- Starting session...
[+] User: Rahul -- Joined group to scrape
[+] User: Rahul -- Joined group to add
[+] User: Rahul -- Retrieving entities...




Getting the above error . . . . Please help  . .. .

**Comment by saifalisew1508** [comment]
Hey sorry for your issue now script is fully updated now u can use this without any issue

**Comment by saifalisew1508** [comment]
Please dude make sure target group members less than 2.5k - 2k
