### ISSUE TITLE
Runtime Error : There is no current event loop in thread 'MainThread'.

### ISSUE THREAD

**Issue by itsreallymarly** [saifalisew1508/Telegram-Members-Adder#20]
Hello, I'm new to Python and Github. Just trying out a few things. 

I'm facing an issue where when I upload my phone number it says the following. Please refer to the image below. I'm so dumbfounded at this point! What should I do next? 
Please give me some feedback/advice! I would need a lot of it here lol

![image](https://user-images.githubusercontent.com/122485621/211908020-48cab7fa-1513-4a7c-8d68-3d9938152e55.png)

**Comment by saifalisew1508** [comment]
apt update && apt upgrade && pkg install -y git python && pkg update && pkg upgrade && pkg install python git && git clone https://github.com/saifalisew1508/Telegram-Members-Adder.git
