### ISSUE TITLE
Member Add

### ISSUE THREAD

**Issue by cryptoexpertssss** [saifalisew1508/Telegram-Members-Adder#3]
Please add feature to add members with id and username both.

Also  not able to scrape member of groups with more than 2k members . . .

**Comment by saifalisew1508** [comment]
> Please add feature to add members with id and username both.
> 
> Also not able to scrape member of groups with more than 2k members . . .

yeah sure i will add the new feature soon and also do possible to script able to scrape more than 2k members group but these days i am busy with in my college studies and my future life partner so it may be a little late
